name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip -q install --upgrade pip
        pip -q install -r requirements.txt
        pip install pandas==1.0.5
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8.0 `ls -R|grep .py$|grep -v h5py | xargs`
    - name: Testing code with unittest
      run: |
        python -m unittest tests/test.py
